### ISSUE TITLE
Postgresql perform keyword

### ISSUE THREAD

**Issue by tbeck-leai** [alex-hhh/emacs-sql-indent#101]
Is there an easy configuration to make the perform keyword in pl/pgsql functions behave the same as select?  Currently if I have the select-clause indent at 0, select clauses look like I want:

```
  select
    column_a,
    column_b
  from
    table_1
  where
    column_a = 1;
```

but replace the select with perform and from and what no longer line up.

```
 perform
    column_a,
    column_b
    from
    table_1
    where
    column_a = 1;
```

**Comment by alex-hhh** [comment]
I added support for the perform keyword -- note that this is only active if the sql-product is set to `'postgres` in your SQL files (you'll know if it isn't when the pefrorm keyword is not highlighted...).  Can you please try it out?  Thanks.

**Comment by tbeck-leai** [comment]
Looks to be working now.  Thanks!
