### ISSUE TITLE
Postgresql end if indentation

### ISSUE THREAD

**Issue by ghost** [alex-hhh/emacs-sql-indent#102]
In a pl/pgsql function, the if statements are ended with `end if`.   These currently are being indented at the body level of the if statement, or I don't have the mode configured properly.

```
  if (not found)
  then
    raise notice 'Not found';
    return 1;
    end if;
```

**Comment by alex-hhh** [comment]
Thanks for reporting this.  I pushed a fix for it and should now work correctly.
