### ISSUE TITLE
drop column if exists considered as an if block

### ISSUE THREAD

**Issue by Golgafrinchan** [alex-hhh/emacs-sql-indent#109]
`column` does not seem to be in the list of keywords _classified_ as STUFF in `sqlind-good-if-candidate` ;)

therefore something like

```sql
alter table sometable drop column if exists col;
```

opens an `if` block

**Comment by alex-hhh** [comment]
Thanks for reporting this.  I pushed a repair, can you please check to see if it works for you?  Thanks, Alex.

**Comment by Golgafrinchan** [comment]
yes, that's exactly it
thank you very much
