### ISSUE TITLE
forward-sexp: Scan error: "Unbalanced parentheses", 151, 1

### ISSUE THREAD

**Issue by PierreTechoueyres** [alex-hhh/emacs-sql-indent#15]
If you put your cursor at the beginning of ```--  return boolean``` and hit the [tab] key you get the error :
«forward-sexp: Scan error: "Unbalanced parentheses", 151, 1»
I hanven't been able to track this error.

```sql

-- declare
--   function dummy(p_param_1 in     varchar2,
--                  p_param_2 in out varchar2,
--                  p_param_2    out varchar2)
--     return   boolean;
--   end dummy;

--   function dummy_2(p_param_1 out varchar2,
--                    p_param_2 out varchar2,
--                    p_param_2 out varchar2)
--     return   boolean;

--     function dummy_3(p_param_1     varchar2,
--                      p_param_2 in  varchar2,
--                      p_param_2 out varchar2)
--       return   boolean;

--       var1  boolean     := true;
--       var2  number      := 1;
--       var42 varchar2(1) := 'Y';
--     begin
--       if dummy(p_param_1  => val1,
--                p_param_10 => val10) then
--         null;
--       end if;
--     end;
--     /

-- Local Variables:
-- mode: sql
-- tab-width: 2
-- indent-tabs-mode: nil
-- sql-product: oracle
-- eval: (sqlind-setup)
-- End:
```

**Comment by alex-hhh** [comment]
The error is raised by `forward-sexp` when the point is inside a comment (the function is not supposed to be called inside a comment).  This function is called in several places by sql-indent code, so I will need to check which code does the wrong thing.

Unfortunately, I will not have time to look into this until the weekend....

**Comment by PierreTechoueyres** [comment]
I'm already happy you've find enough time to maintain it.
There is no hurry.
Many thank.

**Comment by alex-hhh** [comment]
I pushed a fix for this.  Let me know if you have problems.
