### ISSUE TITLE
statement continuation not detected on assignment inside if..then/elsif..then

### ISSUE THREAD

**Issue by PierreTechoueyres** [alex-hhh/emacs-sql-indent#24]
When an assignment with an statement-continuation occurs below an ```if..then``` the statement continuation is not detected.
This appends with if..then / elsif..then but not with else.
See PR #23 for files.

**Comment by alex-hhh** [comment]
I pushed a fix for this, can you please verify it?  Thanks.

**Comment by PierreTechoueyres** [comment]
Look good to me.
I've tested this with an monster package body file ( ~ 16k lines). Seem to indent correctly.
But it's really slow. Do you know how I can profile the execution to try identifying the culprit ?

**Comment by alex-hhh** [comment]
I will close this issue and open a new one to look at the performance issues.
