### ISSUE TITLE
Indenting with tabs

### ISSUE THREAD

**Issue by arssher** [alex-hhh/emacs-sql-indent#32]
Hi,

Is it possible to configure this package to use tabs for indentation? `sqlind-basic-offset` seems to be just integer variable...

**Comment by alex-hhh** [comment]
Yes.  This package uses the Emacs conventions for the actual indentation, and `indent-tabs-mode` controls whether spaces or tabs are inserted (this is true for all programming modes).  You will need to:

* set `indent-tabs-mode` to `t`
* set `sqlind-basic-offset` to the same value  `tab-width` (by default this is 8)
