### ISSUE TITLE
Comments within CTEs, before select statements, change alignment

### ISSUE THREAD

**Issue by brendan-r** [alex-hhh/emacs-sql-indent#46]
Minor issue, but with a statement such as

```sql
blah as (
  select
    blah,
    blah
  from
    blah
)
```
The syntax of the final line being `((select-table-continuation . 40) (nested-statement-continuation . 9) (statement-continuation . 9))`, adding a comment before the select statement changes the alignment:

```sql
blah as (
  -- blah
  select
  blah,
  blah
  from
  blah
  )
```

The syntax of the final line being  `((nested-statement-continuation . 9) (statement-continuation . 9))`

**Comment by alex-hhh** [comment]
Thanks for reporting this.  I have pushed a fix for it.  Can you please check it? Thanks, Alex.

**Comment by brendan-r** [comment]
The fix works perfectly with 

```
emacs -batch -Q --no-site-file -L . -l sql-indent.el
```

But not with my config, even with all minor modes disabled and custom sqlindent code removed. I'll follow up in #45 to contain the discussion.

**Comment by brendan-r** [comment]
Commits above fix issue; failure to reproduce success was user error. Many thanks!
