### ISSUE TITLE
Consider submitting this to GNU ELPA or otherwise contributing it to Emacs

### ISSUE THREAD

**Issue by phil-s** [alex-hhh/emacs-sql-indent#5]
Emacs has lots of good SQL support already by default, and this could make it even better. This would surely be a nice addition to GNU ELPA, and/or could perhaps be contributed back to Emacs itself, to make it available by default.

**Comment by alex-hhh** [comment]
I tried this a while ago, but the task got lost, see 

https://lists.gnu.org/archive/html/emacs-devel/2015-12/msg00943.html

I will try again, to see how it goes...

**Comment by alex-hhh** [comment]
Just a followup on this,  I'm currently discussing this with the Emacs and SQL mode maintainers.  

They are interested in the package and we are working out some details on what the best way is to add this to Emacs.

**Comment by phil-s** [comment]
Many thanks for following that up.

**Comment by PierreTechoueyres** [comment]
Note that there already is an "sql-indent" package on melpa (https://github.com/bsvingen/sql-indent).
If you want to keep the sqlind prefix, you'll probably have to rename the el files with this prefix.
Another solution is to provide and emacs-sql-indent-pkg.el like the one attached.


[emacs-sql-indent-pkg.el.txt](https://github.com/alex-hhh/emacs-sql-indent/files/1023880/emacs-sql-indent-pkg.el.txt)

**Comment by PierreTechoueyres** [comment]
Sorry, the solution with emacs-sql-indent-pkg.el doesn't seem to work.

**Comment by phil-s** [comment]
`sql-indent.el` and a `sql-indent` symbol prefix seems nicest to me, FWIW.

That library on MELPA seems to have been written by [Alex Schroeder](https://alexschroeder.ch/wiki/Contact) (who runs the Emacs Wiki), and at < 200 lines including comments, it's a relatively small library. I would hazard a guess that Alex might be entirely happy to deprecate his library in favour of a more sophisticated replacement, so the naming conflict may be a non-issue.

**Comment by alex-hhh** [comment]
Even if I rename the package to something else, the two packages are still not compatible, since both of them will install their own `indent-line-function` for `sql-mode`.   This package defines the `sqlind-minor-mode` to enable the syntactic indentation, so it is possible to have this package installed, but not active.  The other sql-indent package, however, will hook itself into the indentation mechanism as soon as it is loaded, so it is not possible to have that package installed but not active.

If both packages are installed at the same time, there would cause unexpected and confusing behavior for the user.   Users can only install one or the other, regardless of how the packages are named.

**Comment by alex-hhh** [comment]
I tried to raise this on the emacs-devel mailing list one last time, see

https://lists.gnu.org/archive/html/emacs-devel/2017-08/msg00142.html

Michael Mauger, who maintains sql.el in the GNU Emacs source, has responded to my email as well..  Regrettably, he chose to email me in private and not on the emacs-devel mailing list, so his response is not publicly available and I will not quote it here.

Anyway, Michael said that the tried `sql-indent` and does not like it.  His opinion is that SQL is too complex and a syntactic indentation mode would not work.  He prefers `sql-mode`, as is, with basic indentation only.

Given his response, I will not pursue this any further.  

If anyone wants to add this package to `GNU Emacs`, `ELPA` or `MELPA`, they are welcome to do so.  For my part, I will continue to support this package here on GitHub.

**Comment by phil-s** [comment]
I'm sorry to hear that. Thank you for trying.

**Comment by PierreTechoueyres** [comment]
@alex-hhh 
I'm sad to read this, but not really surprised ...

Would you post your comment to the emacs-devel list ? At least to explain why you give up, in case someone is asking long time after.

**Comment by alex-hhh** [comment]
this package has been added to GNU ELPA, see http://elpa.gnu.org/packages/sql-indent.html
