### ISSUE TITLE
How to indent nested joins?

### ISSUE THREAD

**Issue by dsedivec** [alex-hhh/emacs-sql-indent#70]
Here's some sample SQL:

```sql
SELECT
    *
FROM
    t1
    JOIN t2
        ON t1.k = t2.k
        AND t1.j = t2.j
    -- Here's a "nested join"
    JOIN (
        t3
        LEFT JOIN t4
            ON t3.k = t4.k
            AND t3.j = t4.j
    )
        ON t1.k = t3.k
        AND t1.k = t4.k
```

I've got this indenting correctly *except* for lines 12 and 13, `ON t3.k = t4.k` and `AND t3.j = t4.j`, respectively.  Can you provide any help as to how I can achieve the indentation style shown above?

[Here is my sql-indent config][1] that produces the above indent, except for the `ON` line which I indented above by hand.  I wish this excerpt of my config were shorter, but I didn't want to leave out anything that could affect your answer.  And of course I'm happy to provide additional explanation of that config, add comments where needed, etc.

[1]: https://gist.github.com/dsedivec/018d4d69f88d4240b42c011a1f1722a8

All of my attempts thus far have been to try to apply the indentation I'd normally get from `select-table-continuation` and `select-join-continuation` inside the parentheses here as appropriate, but I've not yet been successful.

Any guidance you can provide would be appreciated.  Thank you very much!

I am using Emacs from a recent build on the `emacs-26` branch on macOS, using `sql-indent.el` from HEAD (e511ced9075b68 as of this writing).

**Comment by alex-hhh** [comment]
Yes, support for nested join conditions is not very good, but hopefully I can improve that.  I have pushed some changes to the `ah/pr70` branch which will recognize the lines containing "ON" and "AND", plus "OR" and "USING" as `select-join-continuation` syntax, even inside nested statements. 

I am not very happy of recognizing the "AND" keyword as a `select-join-continuation`, as it is really part of the expression for the "ON" clause, but it may be useful for simple conditions such as your example.   I don't really want to write a full expression parser for SQL though, so if you have more complex expressions, you will have to enclose them in brackets for correct indentation.

 Can you please try the changes out and let me know if everything works as expected (I don't have much experience with using JOIN syntax).  I will merge after we sort out any problems.

**Comment by dsedivec** [comment]
Thank you again, sir!  I think this is working much better.  It definitely indents my sample above the way I wanted, and I just tested it on maybe a dozen complex statements and indentation is only improved, no regressions that I've found.

As far as I'm concerned this issue can be closed, but I'll leave this issue open in case you don't want it closed until you merge that PR.

**Comment by dsedivec** [comment]
> I don't really want to write a full expression parser for SQL though, so if you have more complex expressions, you will have to enclose them in brackets for correct indentation.

BTW, I completely sympathize with not wanting to implement an SQL parser in Emacs, and I will try to keep your advice about group things to get the desired indentation in mind.

**Comment by alex-hhh** [comment]
Thanks for verifying this.
