### ISSUE TITLE
Adding a few keywords

### ISSUE THREAD

**Issue by dsedivec** [alex-hhh/emacs-sql-indent#73]
*Edited to add a note about `sqlind-lineup-joins-to-anchor`, below.*

I would like to suggest adding `"full"` to `sqlind-select-join-regexp`, as in `FULL JOIN`.  Example:

```sql
SELECT
    *
FROM
    foo
    FULL JOIN bar
        ON foo.k = bar.k
```

Running on branch ah/pr70 right now, the last line gets anchored to `JOIN` rather than `FULL`.  Adding `"full"` to `sqlind-select-join-regexp` anchors the last line to `FULL`, which is probably what you'd expect.

Also, should function `sqlind-lineup-joins-to-anchor` perhaps avail itself of `sqlind-select-join-regexp`?  Right now it contains its own regexp that includes `\\(inner\\|outer\\|cross\\)`, which is much less comprehensive than the list of possible join types in `sqlind-select-join-regexp`.

Finally, I'd also suggest adding `except` to  `\\(union\\|intersect\\|minus\\)` in `sqlind-select-clauses-regexp`.  Example SQL:

```sql
SELECT
	id
FROM
	foo
EXCEPT
SELECT
	id
FROM
	bar
```

(I actually do use these SQL features—I promise I'm not just coming up with torture cases for you.  Since I saw sql-indent suggested in (I think) Emacs 27's `NEWS` file I've been testing it against random SQL files I've worked with *recently*.  I write... a lot of SQL. 😃)

I would submit a PR but I don't have a current assignment on file with the FSF, so I'm going out of my way not to muddy the waters by submitting "tainted" code.  Hopefully the changes I'm suggesting are obvious, but please let me know if you have questions!

**Comment by alex-hhh** [comment]
I have added the keywords and merged a pull request, this was a simple change.

W.r.t the FSF rules, yes they are somewhat strict, and, while copyright assignment is not a complex process, it does take a long time.  In this case, it was indeed simpler for me to just make these changes.
