### ISSUE TITLE
Incorrect indentation after "drop function if exists"

### ISSUE THREAD

**Issue by Stealthmate** [alex-hhh/emacs-sql-indent#80]
In the following example:

```sql
-- -*- sql-product: postgres; -*-
DROP FUNCTION IF EXISTS test;
       |  -- marker here
```

the marker gets indented even though it should stay at the beginning of the line. Removing `IF EXISTS` fixes it. 

I tried replacing `FUNCTION` with each of the keywords in `sqlind-good-if-candidate` and I noticed the same thing happens with `PROCEDURE` too, but none of the other ones, so I guess it's conflicting with some code that handles function indentation.

**Comment by alex-hhh** [comment]
Thanks for reporting this, I pushed fix to the master branch, can you please verify it.

**Comment by Stealthmate** [comment]
It's indeed fixed! Thank you! :tada:
