### ISSUE TITLE
mysql elseif keyword not recognized

### ISSUE THREAD

**Issue by matteo-l** [alex-hhh/emacs-sql-indent#81]
The indentation of the keyword, `elseif`, used by mysql, is different from the one of the keyword `elsif` used by other sql dialects, as you can see from the following example 

```
IF (SELECT ID
      FROM SomeTable
     WHERE SomeField > 0) IS NULL
THEN
  SET SomeVar = TRUE;
ELSIF
  SET SomeVar = FALSE;
END IF;

IF (SELECT ID
      FROM SomeTable
     WHERE SomeField > 0) IS NULL
THEN
  SET SomeVar = TRUE;
  ELSEIF
    SET SomeVar = FALSE;
  END IF;
```

**Comment by alex-hhh** [comment]
Thanks for reporting this, I pushed  fix to the master branch, can you please verify it.

**Comment by matteo-l** [comment]
The fix works for me.
Thank you
