### ISSUE TITLE
Keywords in comments used for alignment

### ISSUE THREAD

**Issue by jaminsore** [alex-hhh/emacs-sql-indent#83]
Keywords used for alignment are detected inside comments. See the example below for the observed behavior
```sql
SELECT
  Column1,
  Column2,
  -- this is FROM a blog WHERE useful stuff was described
                               Column3,
                               Column4
  FROM Atable
```

The expected behavior is that alignment would be unaffected by comments as below

```sql
SELECT
  Column1,
  Column2,
  -- this is FROM a blog WHERE useful stuff was described
  Column3,
  Column4
  FROM Atable
```

**Comment by alex-hhh** [comment]
Thanks for reporting this, I pushed a fix for it, can you please verify it.

**Comment by jaminsore** [comment]
The issue is fixed, thank you!
