### ISSUE TITLE
Bad indentation for CREATE SCHEMA IF NOT EXISTS

### ISSUE THREAD

**Issue by sfllaw** [alex-hhh/emacs-sql-indent#87]
Test case:
``` sql
-- -*- mode: sql; sql-product: postgres; -*-
CREATE SCHEMA IF NOT EXISTS test;
                  |
```

The cursor is indented to `|`, probably because `SCHEMA` is not matched by:
https://github.com/alex-hhh/emacs-sql-indent/blob/08f0417fd739a789991d739be7d524c419558741/sql-indent.el#L491

**Comment by alex-hhh** [comment]
Thanks for reporting this.  I pushed a fix, can you please verify it and reopen the issue if you encounter any problems.  Thanks, Alex.

**Comment by sfllaw** [comment]
@alex-hhh Confirmed!
