### ISSUE TITLE
PostgreSQL DO blocks throws "end statement closes nothing" when encountering a CREATE statement

### ISSUE THREAD

**Issue by sfllaw** [alex-hhh/emacs-sql-indent#89]
Test case in PostgreSQL:

``` sql
DO $$
  BEGIN
    CREATE TABLE t ();
  END -- end statement closes nothing (40, 40)
$$ LANGUAGE plpgsql;
```

When running `sqlind-indent-line` on the `END` statement, `sqlind-refine-end-syntax` throws the `end statement closes nothing` syntax error.

It looks like after the `CREATE TABLE` statement, sqlind thinks that it is back to `'toplevel`, even though it should be `'in-begin-block`.

**Comment by alex-hhh** [comment]
Thanks for reporting this issue -- it was indeed a defect where create table (and view and index) statements were incorrectly considered to start an SQL block.  I pushed a fix for this. Can you please try it out?  Thanks, Alex.

**Comment by sfllaw** [comment]
Fixed!
