### ISSUE TITLE
Bad indentation for COMMENT ON FUNCTION

### ISSUE THREAD

**Issue by sfllaw** [alex-hhh/emacs-sql-indent#90]
Test case for PostgreSQL:
``` sql
COMMENT ON FUNCTION hello IS 'Returns a greeting.';
COMMENT ON PROCEDURE world IS 'Creates a world.';
```

Sqlind gets confused because `sqlind-maybe-defun-statement` thinks that these are actually `defun-start`. I think the correct solution is to handle this in the same code path that checks if this is a `DROP` statement: https://github.com/alex-hhh/emacs-sql-indent/blob/b6940780678e95af245830dbcd897672ca0a0a4c/sql-indent.el#L815-L821

``` elisp
	  (save-excursion
	    (sqlind-backward-syntactic-ws)

	    ;; Find out if it is a drop procedure or function statement
	    (forward-word -1)
	    (when (looking-at "drop")
	      ;; not a procedure after all.
	      (throw 'exit nil))

	    ;; Find out if it is a comment statement
	    (when (eq sql-product 'postgres)
	      (forward-word -1)
	      (when (looking-at "comment\\(?:[ \t\n\r\f]+\\)on")
	        ;; not a procedure after all.
	        (throw 'exit nil))))
```

**Comment by sfllaw** [comment]
Your fix looks good to me!

**Comment by alex-hhh** [comment]
Thanks for noticing the problem, I fixed it.

**Comment by alex-hhh** [comment]
fixed and merged to master
