### ISSUE TITLE
indent does not work on parenthese group

### ISSUE THREAD

**Issue by stardiviner** [alex-hhh/emacs-sql-indent#94]
```sql
 CREATE TABLE users
   (id VARCHAR(20) PRIMARY KEY,
   first_name VARCHAR(30),
   last_name VARCHAR(30),
   email VARCHAR(30),
   admin BOOLEAN,
   last_login TIME,
   is_active BOOLEAN,
   pass VARCHAR(300));
```

It should be:

```sql
 CREATE TABLE users
   (id VARCHAR(20) PRIMARY KEY,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    email VARCHAR(30),
    admin BOOLEAN,
    last_login TIME,
    is_active BOOLEAN,
    pass VARCHAR(300));
```

**Comment by alex-hhh** [comment]
This is not a bug: different people want their SQL programs indented in different ways, so `sql-indent` allows customizing the indentation, rather than enforcing one indentation style on everybody.

The [sqindent.org](https://github.com/alex-hhh/emacs-sql-indent/blob/master/sql-indent.org) document describes how to customize the indentation to suit your preferences. For example, to indent CREATE TABLE statements like you requested, you will need to use the following customization:

```elisp
(defvar my-sql-indentation
  `((nested-statement-continuation sqlind-lineup-into-nested-statement)
    ,@sqlind-default-indentation-offsets-alist))

(add-hook 'sqlind-minor-mode-hook
          (lambda ()
            (setq sqlind-indentation-offsets-alist  my-sql-indentation)))
```

**Comment by stardiviner** [comment]
Thanks @alex-hhh

**Comment by stardiviner** [comment]
Hi @alex-hhh I check out the document, still can't figure out how to set this align rules for parentheses.

And I `xref` on `sqlind-minor-mode`. I did not found it.
I checked my `sql-indent` package version in packages list:
```
  sql-indent         1.10          installed             indentation of SQL statements

Package sql-indent is installed.

     Status: Installed in ‘sql-indent-1.10/’ (unsigned). Delete
    Version: 1.10
    Summary: indentation of SQL statements
Other versions: 1.10 (marmalade), 1.4 (gnu).
```
Is it old?

**Comment by alex-hhh** [comment]
The package you installed is this one: https://github.com/bsvingen/sql-indent,which I don't maintain.

The package that I maintain is v1.4 from the GNU ELPA.

**Comment by stardiviner** [comment]
I removed `sql-indent` which might from ELPA mirror marable. And installed gnu version 1.4. This time is correct now.

Then I config rules like this:
```lisp
(add-to-list 'sqlind-align-rules '(sqlind-lineup-into-nested-statement
                                     (nested-statement-continuation . 1)
                                     (statement-continuation . 1)))
```

This seems does not work. The document's explaination is kind of confused for me.

I think should this document add some config example for some people might be helpful. WDYT?

**Comment by alex-hhh** [comment]
I already gave you the example for how to configure `sql-indent` to indent CREATE TABLE statements as you wanted.

Also, `sql-indent,org` does not tell you to use `add-to-list` on `sqlind-align-rules` (I just checked, but perhaps you can point me to where it states that?)  The documentation could always use improvement and I welcome any concrete suggestions on how to improve it.

**Comment by alex-hhh** [comment]
> I think should this document add some config example for some people might be helpful. WDYT?

The document does contain an example in the "A Simple Example" section.

**Comment by stardiviner** [comment]
I finally figured it out now. Really take a few time.
Here is the solution:
```elisp
  ;; change align and indentation offset rules
  (setq my-sql-indentation-offsets-alist
        `(
          ;; (nested-statement-continuation  sqlind-use-previous-line-indentation +)
          (nested-statement-continuation sqlind-use-anchor-indentation 1)
          ,@sqlind-default-indentation-offsets-alist))
  (add-hook 'sqlind-minor-mode-hook
            (lambda () (setq sqlind-indentation-offsets-alist my-sql-indentation-offsets-alist)))
```
