### ISSUE TITLE
autoloading failed

### ISSUE THREAD

**Issue by vinurs** [alex-hhh/emacs-sql-indent#98]
i use doom emacs, when i open a sql file, then enable sql mode, it output this error
```
File mode specification error: (error Autoloading file /Users/xxx/.emacs.d/.local/straight/build/sql-indent/sql-indent.el failed to define function sql-indent)
```

**Comment by alex-hhh** [comment]
This package does not define a `sql-indent` function, but a `sqlind-minor-mode` function.  For installation instructions, please see the [readme](https://github.com/alex-hhh/emacs-sql-indent/blob/master/README.md) file.

I am not familiar with doom emacs, if it uses a special installation process, you may want to ask for help on the doom emacs forums.

**Comment by alex-hhh** [comment]
Also, this error can happen if you try to enable the mode using a mode variable, such as placing this at the beginning of the SQL file.

**This will not work:**

```sql
-- -*- mode: sql-indent -*- 
```

**this will also not work**

```sql
-- Local Variables:
-- mode: sql-indent
-- End
```
